### ISSUE TITLE
Zombies get chunk healing, but not bottomless appetite

### ISSUE THREAD

**Issue by anoobindisguise** [Hellmonk/bloatcrawl2#37]
The zombie modifier to species lets them heal with chunks, but it doesn't give them the ghoul ability to eat chunks at all times even when not hungry.

**Comment by alexjurkiewicz** [comment]
Thanks for the report!
Fixed in 0.25-a0-609-g0fc5b61605, which should be on CPO in <1hr and CKO in <24hrs.
