### ISSUE TITLE
Leprechaun is not lucky.

### ISSUE THREAD

**Issue by Rydian** [Hellmonk/bloatcrawl2#39]
**Webtiles, Windows 10, Firefox 71.0**

**0.25-a0-613-gf9050fa**

**DESCRIPTION:**
Leprechaun species does not mention being lucky when A is pressed and the yaml file in the source does not list any mutations (so it does not appear that the lucky mutation will happen from leveling).  Some quick searches through the source show that the species is not mentioned in any unique checks, leading me to believe that it's supposed to have the mutation in order to be lucky.

**EXTRA FILES:**
https://i.imgur.com/i0vIP6o.png

**Comment by alexjurkiewicz** [comment]
whoops. Thanks for the report
