### ISSUE TITLE
All items appear magical when wielded.

### ISSUE THREAD

**Issue by Rydian** [Hellmonk/bloatcrawl2#48]
**Webtiles, Windows 10, Firefox 71.0**

**Bloatcrawl 2 2.2.0**

**DESCRIPTION:**
All wielded items in tiles appear to be magical (for both players and monsters), even when they are all base +0 versions with no brand.

**EXTRA FILES:**
Appearance: https://i.imgur.com/EeCwZeT.png
Actual items: https://i.imgur.com/dt1qhzk.png

**Comment by alexjurkiewicz** [comment]
I think this is due to your browser caching old image tiles after a release. I'm not quite sure why this happens, but try in a private browsing session.
